//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// WinTILD.rc で使用
//
#define IDR_MANIFEST                    1
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_HTML_BRUSHSTYLECOMBOBOX     103
#define IDR_HTML_BRUSHHATCHCOMBOBOX     104
#define IDR_MAINFRAME                   128
#define IDR_WinTILDTYPE                  129
#define IDD_INPUT_DIALOG                131
#define IDI_ICON_RESULT                 132
#define IDD_PARAMETER_DIALOG            134
#define IDD_PROGRESS_DIALOG             135
#define ID_VIEW_INPUTDLG                136
#define ID_VIEW_PARAMETERDLG            137
#define IDD_HISTOGRAM_DIALOG            138
#define ID_VIEW_HISTGRAMDLG             139
#define ID_140                          140
#define ID_EXPORT_BITMAPDIVMSD          143
#define IDD_DOMAIN_PROPERTY             144
#define ID_VIEW_OPTION                  145
#define IDC_MAGNIFY                     149
#define IDD_TRAJECTORY_PROPERTY         151
#define IDD_DIVMSD_PROPERTY             152
#define ID_OPERATE_SELECTALL            153
#define ID_OPERATE_DELETE               154
#define ID_Menu                         155
#define ID_OPERATE_FINDDOMAIN           156
#define ID_OPERATE_UPDATE               157
#define ID_OPERATE_ADDTRAJECTORY        158
#define ID_VIEW_MAGNIFY                 159
#define ID_VIEW_MAGNIFY_100             160
#define ID_VIEW_MAGNIFY_200             161
#define ID_VIEW_MAGNIFY_150             162
#define ID_VIEW_MAGNIFY_125             163
#define ID_VIEW_MAGNIFY_075             164
#define ID_VIEW_MAGNIFY_050             165
#define ID_VIEW_MAGNIFY_025             166
#define ID_VIEW_DETAIL                  167
#define IDD_PROGRESSLIST_DIALOG         168
#define IDD_BRUSH_DIALOG                170
#define IDD_PEN_DIALOG                  171
#define IDD_GENERAL_PROPERTY            172
#define IDD_PLAY_DIALOG                 173
#define IDC_LIST_INPUT                  1000
#define IDC_BUTTON_ADD                  1001
#define IDC_BUTTON_REMOVE               1002
#define IDC_BUTTON_CLEAR                1003
#define IDC_BUTTON_UP                   1004
#define IDC_BUTTON_DOWN                 1005
#define IDC_SLIDER_INPUT_FROM           1006
#define IDC_SLIDER_INPUT_TO             1007
#define IDC_EDIT_INPUT_FROM             1008
#define IDC_EDIT_INPUT_TO               1009
#define IDC_SPIN_INPUT_FROM             1010
#define IDC_SPIN_INPUT_TO               1011
#define IDC_STATIC_FRAMES               1012
#define IDC_SLIDER_WFROM                1013
#define IDC_SLIDER_WTO                  1014
#define IDC_EDIT_WFROM                  1015
#define IDC_EDIT_WTO                    1016
#define IDC_EDIT_THRESHOLD              1017
#define IDC_SPIN_WFROM                  1018
#define IDC_SPIN_WTO                    1019
#define IDC_SPIN_THRESHOLD              1020
#define IDC_SPIN_THRESHOLD_FINE         1021
#define IDC_PROGRESS                    1022
#define IDC_SPIN_CALCAVEFROM            1022
#define IDC_STATIC_MESSAGE              1023
#define IDC_SPIN_CALCAVETO              1023
#define IDC_CHECK_DELETEAFTER           1024
#define IDC_CHECK_DONTSHOW              1025
#define IDC_EDIT_P                      1025
#define IDC_EDIT_RATIO                  1026
#define IDC_SPIN_RATIO                  1027
#define IDC_SPIN_RATIO_FINE             1028
#define IDC_EDIT_SKIP                   1029
#define IDC_SPIN_SKIP                   1030
#define IDC_CHECK_INTERACTIVE           1031
#define IDC_CHECK_USEAVERAGE            1032
#define IDC_EDIT_SMOOTHING              1032
#define IDC_EDIT_CALCAVEFROM            1033
#define IDC_EDIT_CALCAVETO              1034
#define IDC_SPIN_P                      1035
#define IDC_SPIN_FWIDTH                 1035
#define IDC_SPIN_SMOOTHING              1035
#define IDC_SPIN_P_FINE                 1036
#define IDC_BUTTON_GETHISTOGRAM         1036
#define IDC_EDIT_DOMAININDEX            1039
#define IDC_SPIN_DOMAININDEX            1040
#define IDC_EDIT_TRAJECTORY_WIDTH       1042
#define IDC_SPIN_TRAJECTORY_WIDTH       1043
#define IDC_EDIT_TRAJECTORY_HEIGHT      1044
#define IDC_SPIN_TRAJECTORY_HEIGHT      1045
#define IDC_CHECK_TRAJECTORY_SQUARE     1046
#define IDC_EDIT_DIVMSD_SIZE            1047
#define IDC_SPIN_DIVMSD_SIZE            1048
#define IDC_RADIO_USESIZE               1049
#define IDC_RADIO_USEMAGNIFY            1050
#define IDC_EDIT_DIVMSD_MAGNIFY         1051
#define IDC_SPIN_DIVMSD_MAGNIFY         1052
#define IDC_LIST1                       1053
#define IDC_LIST_PROGRESS               1053
#define IDC_BUTTON_DMSD_BASECOLOR       1054
#define IDC_PICTURE_DMSD_BASECOLOR      1055
#define IDC_BUTTON_DMSD_THRESHOLD       1056
#define IDC_PICTURE_DMSD_THRESHOLD      1057
#define IDC_PICTURE_DMSD_STARTLINE      1058
#define IDC_BUTTON_TRAJ_BACKGROUND      1058
#define IDC_BUTTON_TRAJ_PLOTAREA        1058
#define IDC_BUTTON_DMSD_STARTLINE       1059
#define IDC_PICTURE_TRAJ_BACKGROUND     1059
#define IDC_PICTURE_TRAJ_PLOTAREA       1059
#define IDC_PICTURE_DMSD_ENDLINE        1060
#define IDC_PICTURE_TRAJ_MARGIN         1060
#define IDC_COMBO_BRUSH_STYLE           1060
#define IDC_BUTTON_DMSD_ENDLINE         1061
#define IDC_BUTTON_TRAJ_MARGIN          1061
#define IDC_COMBO_BRUSH_HATCH           1061
#define IDC_PICTURE_DMSD_BOUNDARY       1062
#define IDC_PICTURE_TRAJ_FRAME          1062
#define IDC_BUTTON1                     1062
#define IDC_BUTTON_BRUSH_COLOR          1062
#define IDC_BUTTON_GENERAL_BACKGROUND   1062
#define IDC_PLAY_BUTTON_PLAYBACKWARD    1062
#define IDC_BUTTON_DMSD_BOUNDARY        1063
#define IDC_BUTTON_TRAJ_FRAME           1063
#define IDC_PLAY_BUTTON_PLAY2           1063
#define IDC_PLAY_BUTTON_PLAY            1063
#define IDC_PICTURE_BRUSH_COLOR         1064
#define IDC_PICTURE_TRAJ_FROM           1064
#define IDC_PICTURE_DMSD_MARGIN         1064
#define IDC_COMBO_PEN_STYLE             1065
#define IDC_BUTTON_TRAJ_FROM            1065
#define IDC_BUTTON_DMSD_MARGIN          1065
#define IDC_PICTURE_PEN_COLOR           1066
#define IDC_PICTURE_TRAJ_TO             1066
#define IDC_PICTURE_TRAJ_FRAME2         1066
#define IDC_PICTURE_DMSD_FRAME          1066
#define IDC_BUTTON_PEN_COLOR            1067
#define IDC_BUTTON_TRAJ_TO              1067
#define IDC_BUTTON_DMSD_FRAME           1067
#define IDC_EDIT_PEN_WIDTH              1068
#define IDC_PICTURE_TRAJ_BOUNDARY       1068
#define IDC_SPIN_PEN_WIDTH              1069
#define IDC_BUTTON_TRAJ_BOUNDARY        1069
#define IDC_PICTURE_TRAJ_BG             1070
#define IDC_CHECK_TRAJ_DRAW_STARTEND    1071
#define IDC_CHECK_TRAJ_DRAWSTARTEND     1071
#define IDC_CHECK_TRAJ_DRAWCOORDINATES  1072
#define IDC_CHECK_TRAJ_DRAWFROMTO       1073
#define IDC_CHECK_TRAJ_DRAWBOUNDARY     1074
#define IDC_CHECK_TRAJ_DRAWBOUNDARYTEXT 1075
#define IDC_BUTTON_TRAJ_BG              1076
#define IDC_PICTURE_TRAJ_TEXTBG         1077
#define IDC_BUTTON_TRAJ_TEXTBG          1078
#define IDC_STATIC_GENERAL_BACKGROUND   1079
#define IDC_CHECK_TRAJ_BACKGROUND       1080
#define IDC_CHECK_TRAJ_TEXTBG           1081
#define IDC_CHECK_DMSD_DRAWFROMTO       1081
#define IDC_CHECK_DMSD_DRAWLINEMETHOD   1082
#define IDC_PICTURE_TRAJ_LINE1          1082
#define IDC_CHECK_DMSD_DRAWBOUNDARY     1083
#define IDC_BUTTON_TRAJ_LINE1           1083
#define IDC_CHECK_DMSD_DRAWBOUNDARYFRAME 1084
#define IDC_PICTURE_TRAJ_LINE2          1084
#define IDC_CHECK_DMSD_DRAWFROMTOFRAME  1085
#define IDC_BUTTON_TRAJ_LINE2           1085
#define IDC_CHECK_DMSD_DRAWMAGNIFY      1086
#define IDC_PICTURE_TRAJ_LINE3          1086
#define IDC_CHECK_DMSD_DRAWSCALE        1087
#define IDC_BUTTON_TRAJ_LINE3           1087
#define IDC_CHECK_DMSD_TEXTBG           1088
#define IDC_PICTURE_TRAJ_LINE4          1088
#define IDC_PICTURE_DMSD_BG             1089
#define IDC_BUTTON_TRAJ_LINE4           1089
#define IDC_BUTTON_DMSD_BG              1090
#define IDC_PICTURE_TRAJ_LINE6          1090
#define IDC_PICTURE_TRAJ_LINE5          1090
#define IDC_BUTTON_DMSD_TEXTBG          1091
#define IDC_BUTTON_TRAJ_LINE5           1091
#define IDC_PICTURE_DMSD_TEXTBG         1092
#define IDC_CHECK_DMSD_BACKGROUND       1093
#define IDC_EDIT_MAXIMUM                1094
#define IDC_SPIN_MAXIMUM                1096
#define IDC_SPIN_MAXIMUM_FINE           1097
#define IDC_CHECK_DRAW_BOUNDARIES       1099
#define IDC_PICTURE_THRESHOLD_COLOR     1104
#define IDC_SLIDER_THRESHOLD_COLOR      1105
#define IDC_EDIT1                       1106
#define IDC_PLAY_EDIT_CURRENTFRAME      1106
#define IDC_EDIT2                       1107
#define IDC_PLAY_EDIT_ENDFRAME          1107
#define IDC_PLAY_SLIDER                 1109
#define IDC_PLAY_BUTTON_STOP            1110
#define IDC_PLAY_SPIN_CURRENTFRAME      1112
#define IDC_PLAY_STATIC_SLASH           1113
#define IDC_PLAY_EDIT_FPS               1114
#define IDC_PLAY_VIEW                   1115
#define IDC_PLAY_SPIN_FPS               1116
#define IDC_PLAY_TEXT_SCALE             1118
#define IDC_SLIDER1                     1119
#define IDC_PLAY_SLIDER_SCALE           1119
#define IDC_STATIC_SMOOTHING            1120
#define ID_ADDTRAJECTORY                32771
#define ID_CALCMSD                      32772
#define ID_UPDATE                       32773
#define ID_FINDDOMAIN                   32780
#define ID_32781                        32781
#define ID_DOMAIN_RESULT                32782
#define ID_FILE_DOMAIN_RESULT           32783
#define ID_FILE_FOUND_DOMAIN_RESULT     32784
#define ID_32785                        32785
#define ID_VIEW_PLAYDLG                 32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
